### ISSUE TITLE
外部リポジトリの関数がloadされない

### ISSUE THREAD

**Issue by n04ln** [n04ln/diesirae.nvim#7]
submoduleで https://github.com/NoahOrberg/vivid.vim を入れているが、うまくロードできていない。

現状、パッケージマネージャなどで https://github.com/NoahOrberg/vivid.vim も入れないと動作しない

**Comment by NoahOrberg** [comment]
https://github.com/NoahOrberg/diesirae.nvim/commit/0461acd11965095f92c9789a4ccb98716f093140
但し書き追加

**Comment by NoahOrberg** [comment]
特定のディレクトリのみsubmodule化すればよさそう
